- name: register value
  hosts: all
  tasks:
  - name: gethost
    shell: hostnam
    register: URL
    ignore_errors: true
  - name: print hostname
    debug:
      msg: "hello cloud"
  - name: print hostname
    debug:
      msg: "cloudy weather"